### ISSUE TITLE
snowflake wouldn't connect

### ISSUE THREAD

**Issue by ahsbt** [guardianproject/orbot-android#748]
hello
recently im not able to connect orbot through any bridge modes (basically snowflake works on my pc)
it gets stuck at 10% or control port activation in the beginning

but on the same phone with the same connection the tor browser app flawlessly connects to same snowflake settings.
i managed to take a pic from the torbrowser console before 100% connection , and one is from orbot which after many trials gave these warns and errors.

thank you in advance

![photo_2022-10-19_06-57-45](https://user-images.githubusercontent.com/45170538/196590762-16d716c6-973c-4335-bcda-0682f257d546.jpg)
![photo_2022-10-19_06-57-54](https://user-images.githubusercontent.com/45170538/196590792-8be5e5f5-87b9-4148-bef3-38a25b2c33e5.jpg)

**Comment by n8fr8** [comment]
Did you test the new beta we released yesterday?
https://github.com/guardianproject/orbot/releases/tag/16.6.3-BETA-1-tor.0.4.7.10

**Comment by ahsbt** [comment]
Hi yes

**Comment by ahsbt** [comment]
yes sir i still have the apk of the last 4 or 5 versions , all of them not work including 17 alpha and the one you released only couple of hours ago

**Comment by n8fr8** [comment]
Which device / OS are you on?

**Comment by ahsbt** [comment]
sm-g985f/ds
one ui version 4.1
android version 12
google play system update sep 1, 2022
android sec patch also the same sep 1 2022

**Comment by ahsbt** [comment]
https://github.com/guardianproject/orbot/issues/742#issue-1400109078

**Comment by n8fr8** [comment]
Orbot for Android 16.6.3-BETA-2-tor.0.4.7.10 with utls enabled https://github.com/guardianproject/orbot/releases/tag/16.6.3-BETA-2-tor.0.4.7.10

as well as the ability to get Snowflake logs directly from the log window (enable Prefs->DEBUG log, tap on status messages to open log window, tap on snowflake icon to show snowflake log, then share!)

**Comment by n8fr8** [comment]
Thanks, and great news. If you tap the share icon, you can email the log, or send it to gmail, then copy and paste easily from there.

**Comment by ahsbt** [comment]
it connected with both snowflake methods
the AMP mode didnt work for a long time as i remember , but it got connected with this version. 

👌❤

**Comment by n8fr8** [comment]
I posted another beta 3 that uses a different utls-imitate technique, and should now support devices back to Android 7:
https://github.com/guardianproject/orbot/releases/tag/16.6.3-BETA-3-tor.0.4.7.10

Working on adding some other settings to the preferences, so users can have some options for tweaking/tuning. Otherwise, almost ready for a release candidate and to push this out to the world.

**Comment by aaamirG** [comment]
> I posted another beta 3 that uses a different utls-imitate technique, and should now support devices back to Android 7: https://github.com/guardianproject/orbot/releases/tag/16.6.3-BETA-3-tor.0.4.7.10
> 
> Working on adding some other settings to the preferences, so users can have some options for tweaking/tuning. Otherwise, almost ready for a release candidate and to push this out to the world.

I can confirm it Works amazingly in Iran!
Well done!

Shatel ISP and Rightel ISP Tested

**Comment by ahsbt** [comment]
although being a free service , tor support was on another level . very professional , delivering and friendly ... still my all time favor is having a custom dns option inside the app , because i've seen many times that a web page opens without tor , then wont open with a working tor , then opens after changing to couple of other exits which points to dns in my opinion 

thank you for the great work , ❤

**Comment by cyber199** [comment]
Given that this issue is still open and that I'm having a similar problem of not being able to connect using snowflake, can I leave these logs here or would it be better to open a fresh issue?

Logs (which appear to already be scrubbed of private info) follow:
`Snowflake proxy mode enabled
Snowflake proxy mode enabled
updating settings in Tor service
Updating torrc custom configuration…
Orbot is starting…
Connected to tor control port
Added control port event handler
Snowflake proxy mode enabled
WARN: Rejecting SOCKS request for anonymous connection to private address [scrubbed].
NOTICE: Tried for 120 seconds to get a connection to [scrubbed]:0. Giving up. (waiting for circuit)
NOTICE: Tried for 120 seconds to get a connection to [scrubbed]:0. Giving up. (waiting for circuit)
NOTICE: Tried for 120 seconds to get a connection to [scrubbed]:5222. Giving up. (waiting for circuit)
NOTICE: Application request when we haven't used client functionality lately. Optimistically trying known bridges again.
NOTICE: Application request when we haven't used client functionality lately. Optimistically trying known bridges again.
NOTICE: Application request when we haven't used client functionality lately. Optimistically trying known bridges again.
NOTICE: Application request when we haven't used client functionality lately. Optimistically trying known bridges again.
NOTICE: Application request when we haven't used client functionality lately. Optimistically trying known bridges again.
NOTICE: Application request when we haven't used client functionality lately. Optimistically trying known bridges again.
NOTICE: Application request when we haven't used client functionality lately. Optimistically trying known bridges again.
NOTICE: Application request when we haven't used client functionality lately. Optimistically trying known bridges again.
NOTICE: Application request when we haven't used client functionality lately. Optimistically trying known bridges again.
NOTICE: Application request when we haven't used client functionality lately. Optimistically trying known bridges again.
NOTICE: Application request when we haven't used client functionality lately. Optimistically trying known bridges again.
NOTICE: Application request when we haven't used client functionality lately. Optimistically trying known bridges again.
NOTICE: Application request when we haven't used client functionality lately. Optimistically trying known bridges again.
NOTICE: Application request when we haven't used client functionality lately. Optimistically trying known bridges again.
NOTICE: Application request when we haven't used client functionality lately. Optimistically trying known bridges again.
NOTICE: Application request when we haven't used client functionality lately. Optimistically trying known bridges again.
NOTICE: Application request when we haven't used client functionality lately. Optimistically trying known bridges again.
NOTICE: Application request when we haven't used client functionality lately. Optimistically trying known bridges again.
NOTICE: Application request when we haven't used client functionality lately. Optimistically trying known bridges again.
NOTICE: Application request when we haven't used client functionality lately. Optimistically trying known bridges again.
NOTICE: Application request when we haven't used client functionality lately. Optimistically trying known bridges again.
NOTICE: Application request when we haven't used client functionality lately. Optimistically trying known bridges again.
NOTICE: Application request when we haven't used client functionality lately. Optimistically trying known bridges again.
NOTICE: Application request when we haven't used client functionality lately. Optimistically trying known bridges again.
NOTICE: Application request when we haven't used client functionality lately. Optimistically trying known bridges again.
NOTICE: Tried for 120 seconds to get a connection to [scrubbed]:0. Giving up. (waiting for circuit)
NOTICE: Tried for 120 seconds to get a connection to [scrubbed]:443. Giving up. (waiting for circuit)
NOTICE: Tried for 120 seconds to get a connection to [scrubbed]:0. Giving up. (waiting for circuit)
`

I cant tell if it is broken or if I need to be more patient.

**Comment by syphyr** [comment]
https://github.com/guardianproject/orbot/issues/1011#issuecomment-1817906145

**Comment by cyber199** [comment]
> [#1011 (comment)](https://github.com/guardianproject/orbot/issues/1011#issuecomment-1817906145)

This appears to be related to snowflake in the Kindness tab, I was unable to connect via snowflake under the Connection tab.  Updating Orbot to the version provided from Github solved this issue, so I assume the problem lies in the latest F-Droid version being out of date.

**Comment by bitmold** [comment]
Closing this because while connecting via snowflake is always a bit of a cat and mouse with your local censor, the original issue has been dealt with a while ago and I'm able to connect with snowflake as a bridge right now.

**Comment by Muaytie666** [comment]
SoSoValue’s High-Performance Layer 1 "SoDEX" Opens to Public, Backed by 150M $SOSO Incentive Pool
Explore more key information on SoSoValue:
https://sosovalue.com/shares/93PHrR
XRP spot ETF had a net outflow of $52.26 million this week
Explore more key information on SoSoValue:
https://sosovalue.com/shares/H6YG
